package dev.khoj.pitaka.data.crypto.aead

import javax.crypto.Cipher
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/**
 * AES-256-GCM implementation of [Aead].
 *
 * The wrapping [SecretKey] is supplied by the caller. In production that key
 * is the non-exportable Android Keystore key handed over by
 * [KeystoreKeyProvider]; in unit tests it is a plain in-memory JCE key
 * (`KeyGenerator.getInstance("AES").generateKey()`), which is what makes the
 * crypto here testable off-device — the project has no Robolectric
 * `AndroidKeyStore`, so the Keystore provisioning stays a thin boundary
 * (verified on-device) and the algorithm lives here, fully unit-tested.
 *
 * Format (identical to KeystoreVault v1, the app's single at-rest shape):
 *   12-byte random IV (GCM standard) || ciphertext || 16-byte GCM tag.
 * The IV is generated by the JCE provider per [encrypt] call — never reused
 * for a given key, which is the one invariant AES-GCM cannot survive losing.
 */
class AesGcmAead(
    private val key: SecretKey,
) : Aead {

    override fun encrypt(plaintext: ByteArray, associatedData: ByteArray): ByteArray {
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.ENCRYPT_MODE, key)
        val iv = cipher.iv
        require(iv.size == IV_BYTES) { "Unexpected GCM IV size: ${iv.size}" }
        if (associatedData.isNotEmpty()) cipher.updateAAD(associatedData)
        val ct = cipher.doFinal(plaintext)
        return ByteArray(iv.size + ct.size).also {
            System.arraycopy(iv, 0, it, 0, iv.size)
            System.arraycopy(ct, 0, it, iv.size, ct.size)
        }
    }

    override fun decrypt(ciphertext: ByteArray, associatedData: ByteArray): ByteArray {
        require(ciphertext.size > IV_BYTES) { "Ciphertext too short to contain an IV" }
        val iv = ciphertext.copyOfRange(0, IV_BYTES)
        val ct = ciphertext.copyOfRange(IV_BYTES, ciphertext.size)
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.DECRYPT_MODE, key, GCMParameterSpec(TAG_BITS, iv))
        if (associatedData.isNotEmpty()) cipher.updateAAD(associatedData)
        // Throws AEADBadTagException on tamper / wrong key / wrong AAD.
        return cipher.doFinal(ct)
    }

    companion object {
        const val TRANSFORMATION = "AES/GCM/NoPadding"
        const val IV_BYTES = 12
        const val TAG_BITS = 128
    }
}
