package dev.khoj.pitaka.data.images

/**
 * Pure planner for the one-shot cover heal (PLAN-covers.md D4).
 *
 * Background: before the D1 rework, a book's `coverUrl` stored an absolute
 * path whose filename was the autogenerated book id
 * (`file:///…/covers/<id>.jpg`). Export/import (id reset) and backup (no cover
 * bytes) left rows pointing at stale, missing, or *shared* filenames — two
 * books could reference the same file, so a freshly-scanned cover appeared on
 * both. This planner rationalises that legacy state exactly once.
 *
 * Policy (locked decision D4), applied per book that has a LOCAL cover:
 *  - **unsafe reference** (traversal / nested / protocol smuggling) → clear it.
 *  - **file missing** on disk → clear it (the bytes are gone; nothing to show).
 *  - **file shared** by 2+ rows → clear it (ownership is unknowable; never
 *    guess which book truly owns a shared file — that guess is the original
 *    bug).
 *  - **file present AND uniquely referenced**:
 *      - already a valid relative `covers/<uuid>.jpg` → keep unchanged.
 *      - legacy absolute `file://…` → salvage: rename the file to a fresh
 *        `covers/<uuid>.jpg` and rewrite the row to that relative reference.
 *
 * Remote (`https://`) and null covers are not local and are never touched.
 *
 * Orphan cleanup: any existing cover file that no surviving row references
 * (e.g. a shared file whose rows were all cleared) is scheduled for deletion
 * to reclaim space. Files consumed by a salvage rename are not double-counted.
 *
 * The planner is total and side-effect free: it returns a [CoverHealPlan] the
 * caller applies. This makes the risky data-migration logic exhaustively
 * unit-testable without a device or filesystem.
 */
object CoverHealPlanner {

    data class Input(val id: Long, val coverUrl: String?)

    sealed interface RowAction {
        /** Set the row's coverUrl to null. */
        data class Clear(val id: Long) : RowAction
        /** Set the row's coverUrl to [newCoverUrl] (a relative covers/ ref). */
        data class Rewrite(val id: Long, val newCoverUrl: String) : RowAction
    }

    /** Move the on-disk file [fromLeaf] → [toLeaf] (both bare filenames). */
    data class FileRename(val fromLeaf: String, val toLeaf: String)

    data class Plan(
        val rowActions: List<RowAction>,
        val fileRenames: List<FileRename>,
        val deleteLeaves: List<String>,
    ) {
        val isEmpty: Boolean
            get() = rowActions.isEmpty() && fileRenames.isEmpty() && deleteLeaves.isEmpty()
    }

    /**
     * @param inputs all book rows (id + coverUrl).
     * @param existingLeaves the set of filenames currently in filesDir/covers/.
     * @param newUuid supplies a fresh UUID for each salvaged cover (seam for
     *        deterministic tests).
     */
    fun plan(
        inputs: List<Input>,
        existingLeaves: Set<String>,
        newUuid: () -> String,
    ): Plan {
        val localRows = inputs.filter { CoverPaths.isLocal(it.coverUrl) }

        // How many local rows reference each leaf (shared-ownership detection).
        val leafRefCount = HashMap<String, Int>()
        for (r in localRows) {
            val leaf = CoverPaths.leafOf(r.coverUrl) ?: continue
            leafRefCount[leaf] = (leafRefCount[leaf] ?: 0) + 1
        }

        val rowActions = mutableListOf<RowAction>()
        val fileRenames = mutableListOf<FileRename>()
        val keptLeaves = mutableSetOf<String>()    // files referenced after heal
        val salvageSources = mutableSetOf<String>() // legacy files being renamed away

        for (r in localRows) {
            val leaf = CoverPaths.leafOf(r.coverUrl)
            if (leaf == null) {
                rowActions += RowAction.Clear(r.id)
                continue
            }
            val present = leaf in existingLeaves
            val shared = (leafRefCount[leaf] ?: 0) > 1
            if (!present || shared) {
                rowActions += RowAction.Clear(r.id)
                continue
            }
            // present && uniquely referenced
            val alreadyRelative = r.coverUrl!!.trim().startsWith(CoverPaths.PREFIX)
            if (alreadyRelative) {
                keptLeaves += leaf // valid post-D1 reference; leave it alone
            } else {
                val uuid = newUuid()
                val toLeaf = "$uuid.jpg"
                fileRenames += FileRename(fromLeaf = leaf, toLeaf = toLeaf)
                salvageSources += leaf
                keptLeaves += toLeaf
                rowActions += RowAction.Rewrite(r.id, CoverPaths.relativeFor(uuid))
            }
        }

        // Orphans: existing files neither kept as-is nor consumed by a rename.
        val deleteLeaves = existingLeaves
            .filter { it !in keptLeaves && it !in salvageSources }
            .sorted()

        return Plan(rowActions = rowActions, fileRenames = fileRenames, deleteLeaves = deleteLeaves)
    }
}
